restylers:
  - prettier:
      image: tehalexf/prettier-restyler:v4
      include:
        - "**/*.ts"
        - "**/*.tsx"
        - "**/*.js"
        - "**/*.jsx"
      command: [prettier, --write]
  - "*"
