restylers:
  - prettier:
      image: tehalexf/prettier-restyler:v4
      include:
        - "**/*.ts"
        - "**/*.tsx"
        - "**/*.js"
        - "**/*.jsx"
        - "!**/layout.tsx"
        - "!**/tailwind.config.ts"
      command: [prettier, --write]
  - "*"
