#!/usr/bin/env bash
yarn link tailwindcss
yarn link typescript
yarn link prettier-plugin-organize-imports
yarn link prettier-plugin-tailwindcss
trap 'yarn unlink typescript' EXIT
trap 'yarn unlink tailwindcss' EXIT
trap 'yarn unlink prettier-plugin-organize-imports' EXIT
trap 'yarn unlink prettier-plugin-tailwindcss' EXIT
prettier "$@"